spring:
    application:
        name: ecommerce
    
    jpa:
        hibernate:
            ddl-auto: update
        # Estas configuraciones de aqui son utiles en caso de necesitar ver las inserciones que hace a la bd
        #     naming:
        #         physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy 
        # properties:
        #     hibernate:
        #         format_sql: true
        #         highlight_sql: true
        #         show_sql: true
        #         use_sql_comments: true

    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        username: ecommerce
        password: Oracle.1234567890

server:
    port: 5600
